Fix getBtcBalance wrapper response
RGB-Tools/rgb-lib-nodejs pull request #5
Opened 2024-12-07 15:12 UTC by tmalahie

The method getBtcBalance returns the data as a string instead of an object. All similar methods do a `JSON.parse` before to return an object.
This PR resolves the inconsistency by adding the missing JSON.parse

2024-12-09 09:58 UTC, zoedberg commented
As we discussed in https://github.com/RGB-Tools/rgb-lib-nodejs/pull/2, node.js suffers float rounding errors, therefore we decided to get and return all numbers as strings. Then we suggest that users parse those strings with some specific library, as big.js. Therefore I'm closing this PR

2024-12-09 10:03 UTC, zoedberg commented
Oops, sorry, my mistake. I forgot that the `get_btc_balance` returns an object and not a single amount. I'm afraid though that the parsing will not convert the numbers to strings. So we should implement something like we did for getting the numbers as strings (i.e. `#[serde(deserialize_with = "from_str_or_number_optional")]`). Therefore I'll reopen this PR

2024-12-09 10:53 UTC, nicbus requested changes
a couple points:
- please format the code
- in `example.js`, please call `JSON.stringify` on `btcBalance` so it gets properly displayed

2024-12-11 13:10 UTC, zoedberg requested changes
The changes look good, thanks. Please squash the commits into a single signed one, then I'll merge this

2024-12-12 10:18 UTC, zoedberg approved these changes
LGTM, thank you!

2024-12-12 10:18 UTC, merged